# Generated by Django 5.2.13 on 2026-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='temp Name', max_length=255),
            preserve_default=False,
        ),
    ]
